# Generated by Django 4.0 on 2021-12-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenido', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='contenido',
        ),
    ]
